[colors.primary]
background = "#000000"
foreground = "#ffffff"

[cursor.style]
shape = "Beam"

[font]
size = 11.0

[font.bold]
family = "AnonymicePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "AnonymicePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "AnonymicePro Nerd Font"
style = "Italic"

[font.normal]
family = "AnonymicePro Nerd Font"
style = "Normal"

[shell]
program = "/usr/bin/zsh"

[window.padding]
x = 20
y = 20
